apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: amd64
spec:
  template:
    metadata:
      labels:
        type: karpenter
        provisioner: amd64
        NodeGroupType: amd64
    spec:
      taints:
        - key: amd64
          effect: NoSchedule
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "eks.amazonaws.com/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: Gt
          values: ["4"]
      nodeClassRef:
        name: basic
        group: eks.amazonaws.com
        kind: NodeClass
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
    budgets:
      - nodes: "10%"
        # Cron schedule: Start at 6 PM EST (11 PM UTC) daily
        schedule: "0 23 * * *"
        duration: 8h
        # Disruptions allowed from 6 PM to 2 AM EST (23:00-07:00 UTC)
        # This is outside US business hours (9 AM - 6 PM EST)
      - nodes: "0"
        # No disruptions during US business hours (2 AM - 6 PM EST)
        schedule: "0 7 * * *"
        duration: 16h
  limits:
    cpu: 1000