---
# Namespace and Resource Quota Application
# Creates namespaces and resource quotas for all environments
# Sync wave 2 - must happen before ApplicationSets

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment-namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rsvivek25/argocd-pilot-practice
    targetRevision: main
    path: environments/cldev01
    directory:
      recurse: false
      include: '{namespace.yaml,resource-quota.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
