---
# ArgoCD Root Application (App of Apps)
# This is the bootstrap application that manages all other applications
# Apply this first: kubectl apply -f argocd/root-app.yaml
#
# This root app discovers and applies:
# 1. Platform infrastructure (storage, node pools) from argocd/platform-apps.yaml
# 2. Environment namespaces from environments/*/namespace.yaml & resource-quota.yaml
# 3. ApplicationSets from environments/*/applicationset.yaml
#    (which then auto-generate workload applications)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/rsvivek25/argocd-pilot-practice
    targetRevision: main
    path: argocd
    directory:
      recurse: false
      include: '*.yaml'
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true       # Remove resources not in Git
      selfHeal: true    # Sync when cluster state drifts from Git
    syncOptions:
      - CreateNamespace=true  # Allow creating namespaces
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences in certain fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore if using HPA
